<a href="https://colab.research.google.com/github/JASMINPATNAIK/DMDW-Lab/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib','inline')

In [7]:

url="https://raw.githubusercontent.com/Anasuya-Sahoo/DMDW-Lab/main/student-mat.csv"

In [8]:
df=pd.read_csv(url,sep=',')
dfn=df[['traveltime','studytime']]
dfn.head()

   traveltime  studytime
0           2          2
1           1          2
2           1          2
3           1          3
4           1          2

In [29]:
numeric=df[['age','Medu','traveltime','studytime','failures']]
numeric.head()

   age  Medu  traveltime  studytime  failures
0   18     4           2          2         0
1   17     1           1          2         0
2   15     1           1          2         3
3   15     4           1          3         0
4   16     3           1          2         0

In [30]:
num1=np.array(numeric[['age','failures']])

In [31]:
num1.reshape(-1,2)

array([[18,  0],
       [17,  0],
       [15,  3],
       [15,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [17,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [17,  3],
       [16,  0],
       [15,  0],
       [15,  0],
       [16,  0],
       [16,  0],
       [15,  0],
       [16,  2],
       [15,  0],
       [15,  0],
       [16,  0],
       [16,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [16,  0],
       [15,  0],
       [15,  0],
       [16,  0],
       [15,  0],
       [15,  0],
       [16,  1],
       [15,  0],
       [15,  0],
       [15,  0],
       [16,  1],
       [15,  0],
       [16,  0],
       [16,  0],
       [15,  0],
       [15,  1],
       [16,  0],
       [15,  0],
       [15,  1],
       [15,  0],
       [15,  0],
       [16,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [15,  0],
       [16,  0],
       [15,  0],
       [16,  0],
       [15,  0],
       [15,  0],
       [16,  0],
       [15,  0],
       [15,  2],
       [16,  0],
       [16,  0],
       [15,  0],
       [15,  0],
       [16,  0],
       [17,  3],
       [16,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  2],
       [16,  0],
       [15,  0],
       [16,  1],
       [16,  0],
       [16,  0],
       [15,  0],
       [16,  0],
       [16,  0],
       [15,  0],
       [15,  1],
       [16,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [15,  0],
       [16,  0],
       [15,  0],
       [16,  0],
       [15,  0],
       [16,  1],
       [16,  1],
       [15,  0],
       [15,  0],
       [16,  0],
       [15,  0],
       [16,  0],
       [17,  1],
       [15,  0],
       [15,  0],
       [15,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [15,  0],
       [15,  0],
       [19,  3],
       [18,  2],
       [16,  0],
       [15,  2],
       [15,  0],
       [17,  0],
       [16,  0],
       [15,  0],
       [15,  0],
       [17,  0],
       [16,  2],
       [16,  1],
       [15,  0],
       [15,  0],
       [16,  2],
       [15,  0],
       [16,  0],
       [17,  3],
       [15,  0],
       [15,  3],
       [15,  0],
       [16,  0],
       [15,  3],
       [18,  3],
       [16,  1],
       [15,  2],
       [19,  3],
       [17,  0],
       [15,  0],
       [17,  0],
       [18,  3],
       [16,  0],
       [16,  1],
       [17,  2],
       [15,  2],
       [16,  1],
       [17,  0],
       [17,  3],
       [16,  1],
       [16,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [16,  2],
       [16,  0],
       [17,  0],
       [16,  3],
       [16,  0],
       [17,  0],
       [16,  0],
       [17,  0],
       [16,  0],
       [17,  0],
       [16,  0],
       [16,  0],
       [17,  0],
       [17,  0],
       [16,  0],
       [17,  0],
       [16,  0],
       [16,  0],
       [17,  0],
       [17,  0],
       [16,  0],
       [17,  0],
       [17,  0],
       [16,  0],
       [16,  0],
       [17,  0],
       [17,  0],
       [16,  0],
       [17,  1],
       [16,  0],
       [16,  0],
       [16,  0],
       [17,  0],
       [17,  0],
       [16,  0],
       [17,  1],
       [16,  3],
       [16,  0],
       [16,  0],
       [17,  0],
       [19,  0],
       [17,  0],
       [16,  0],
       [18,  1],
       [17,  0],
       [17,  0],
       [17,  2],
       [18,  1],
       [17,  0],
       [17,  0],
       [17,  0],
       [17,  1],
       [16,  0],
       [18,  0],
       [16,  0],
       [18,  1],
       [17,  0],
       [17,  0],
       [18,  0],
       [17,  0],
       [17,  0],
       [17,  0],
       [17,  0],
       [16,  0],
       [16,  0],
       [16,  0],
       [17,  0],
       [16,  0],
       [17,  0],
       [18,  1],
       [17,  0],
       [17,  0],
       [16,  0],
       [16,  0],
       [18,  0],
       [16,  0],
       [17,  0],
       [22,  3],
       [18,  1],
       [16,  0],
       [18,  1],
       [16,  0],
       [18,  1],
       [16,  0],
       [17,  0],
       [17,  1],
       [17,  0],
       [19,  0],
       [18,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [18,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [18,  0],
       [19,  2],
       [18,  0],
       [18,  0],
       [17,  0],
       [17,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [18,  1],
       [18,  0],
       [17,  0],
       [17,  1],
       [18,  0],
       [18,  0],
       [17,  0],
       [17,  0],
       [18,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [18,  0],
       [17,  0],
       [18,  1],
       [17,  0],
       [18,  0],
       [17,  0],
       [19,  0],
       [18,  0],
       [18,  0],
       [18,  0],
       [18,  0],
       [17,  0],
       [17,  0],
       [17,  0],
       [19,  1],
       [18,  1],
       [20,  0],
       [19,  1],
       [19,  1],
       [19,  1],
       [19,  1],
       [19,  0],
       [19,  1],
       [19,  1],
       [19,  2],
       [19,  1],
       [18,  0],
       [18,  0],
       [17,  0],
       [18,  0],
       [17,  0],
       [17,  0],
       [17,  0],
       [17,  0],
       [17,  0],
       [18,  0],
       [17,  0],
       [17,  0],
       [17,  0],
       [17,  0],
       [18,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [18,  0],
       [17,  0],
       [19,  1],
       [17,  0],
       [18,  0],
       [17,  0],
       [19,  1],
       [18,  1],
       [18,  0],
       [17,  1],
       [18,  0],
       [18,  0],
       [18,  0],
       [18,  0],
       [17,  0],
       [18,  1],
       [19,  3],
       [17,  0],
       [18,  1],
       [19,  1],
       [17,  0],
       [18,  0],
       [17,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [18,  0],
       [18,  1],
       [18,  0],
       [17,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [17,  1],
       [18,  0],
       [18,  0],
       [19,  2],
       [18,  0],
       [17,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [20,  2],
       [18,  0],
       [18,  0],
       [17,  0],
       [18,  0],
       [18,  0],
       [17,  0],
       [19,  1],
       [18,  1],
       [18,  0],
       [18,  0],
       [19,  1],
       [18,  0],
       [18,  1],
       [20,  2],
       [17,  0],
       [21,  3],
       [18,  0],
       [19,  0]])

In [32]:
num1.shape

(395, 2)